export const Packages = {
  Ontario: [
    {
      name: "Basic",
      price: "$99",
      color: "primary",
      description: "Perfect for regular maintenance",
      borderColor: "gray-200",
      note: "Applicable for One Gas Furnace",
      features: [
        "Unlimited Duct Cleaning",
        "Unlimited Vents Cleaning",
        "Main Line Cleaning",
        "Herbal Sanitizer Spray",
        "Inspection of Furnace, Dryervent, AC etc.",
      ],
      buttonClass: "btn-primary",
    },
    {
      name: "Premium",
      price: "$199",
      color: "secondary",
      description: "Comprehensive cleaning solution",
      borderColor: "secondary-500",
      isPopular: true,
      note: "Applicable for One Gas Furnace",
      features: [
        "Unlimited Duct Cleaning",
        "Unlimited Vents Cleaning",
        "DryerVent Cleaning",
        "Natural Disinfectant Spray",
        "Furnace Cleaning.",
        "Inspection of AC Coil, Exhaust fan etc.",
      ],
      buttonClass: "btn-secondary",
    },
    {
      name: "Deluxe",
      price: "$399",
      color: "accent",
      description: "Complete premium service",
      borderColor: "gray-200",
      note: "Applicable for One Gas Furnace",
      features: [
        "Unlimited Duct Cleaning",
        "Unlimited Vents Cleaning",
        "DryerVent/Exhaust Fan Cleaning",
        "Brushing Service",
        "Furnace/AC Coil Cleaning",
        "Natural Disinfectant Spray",
      ],
      buttonClass: "btn-accent",
    },
  ],

  Alberta: [
    {
      name: "Basic",
      price: "$149",
      color: "primary",
      description: "Perfect for regular maintenance",
      borderColor: "gray-200",
      note: "Applicable for One Gas Furnace",
      features: [
        "Unlimited Duct Cleaning",
        "Unlimited Vents Cleaning",
        "Herbal Sanitization Spray",
        "Free Dryer Vent Inspection",
        "Free Furnace & AC Inspection",
      ],
      buttonClass: "btn-primary",
    },
    {
      name: "Premium",
      price: "$199",
      color: "secondary",
      description: "Comprehensive cleaning solution",
      borderColor: "secondary-500",
      isPopular: true,
      note: "Applicable for One Gas Furnace",
      features: [
        "Unlimited Duct Cleaning",
        "Unlimited Vents Cleaning",
        "Dryer & Dryer Vent Cleaning",
        "Herbal Benefect Sanitizer",
        "Free Furnace Inspection",
        "Free AC/Coil Inspection",
      ],
      buttonClass: "btn-secondary",
    },
    {
      name: "Deluxe",
      price: "$399",
      color: "accent",
      description: "Complete premium service",
      borderColor: "gray-200",
      note: "Applicable for One Gas Furnace",
      features: [
        "Unlimited Duct Cleaning",
        "Unlimited Vents Cleaning",
        "Furnace Cleaning",
        "Dryer Vent Cleaning",
        "AC Coil Cleaning",
        "Main Line Cleaning",
        "Brushing / Scrubbing Service",
        "Herbal Sanitization Treatment",
        "Before & After Pictures Provided",
      ],
      buttonClass: "btn-accent",
    },
  ],
};


export const Deals = {
  Ontario: [
    {
      dealTitle: "Starter Clean",
      services: ["Unlimited Ducts", "Unlimited Vents", "Dryer Vent"],
      price: "$115",
      savings: "Save $30",
    },
    {
      dealTitle: "Essential Care",
      services: ["Unlimited Ducts", "Unlimited Vents", "Furnace", "Dryer Vent"],
      price: "$169",
      savings: "Save $50",
    },
    {
      dealTitle: "Complete Home",
      services: [
        "Unlimited Ducts",
        "Unlimited Vents",
        "Furnace",
        "Dryer Vent",
        "Return Line",
      ],
      price: "$199",
      savings: "Save $75",
    },
    {
      dealTitle: "Premium Service",
      services: [
        "Unlimited Ducts",
        "Unlimited Vents",
        "Dryer Vent",
        "Furnace",
        "Return Line",
        "Brushing Service",
      ],
      price: "$259",
      savings: "Save $100",
      popular: true,
    },
    {
      dealTitle: "Ultimate Package",
      services: [
        "Unlimited Ducts",
        "Unlimited Vents",
        "Dryer Vent",
        "Furnace",
        "Return Line",
        "Brushing Service",
        "AC Coil Cleaning",
      ],
      price: "$319",
      savings: "Save $130",
    },
  ],

  Alberta: [
    {
      dealTitle: "Essential Package",
      services: ["Unlimited Ducts", "Unlimited Vents", "Dryer Vent Cleaning"],
      price: "$165",
      savings: "Save $30",
    },
    {
      dealTitle: "Comfort Package",
      services: [
        "Unlimited Ducts",
        "Unlimited Vents",
        "Duct Cleaning",
        "Furnace Cleaning",
        "Dryer Vent Cleaning",
      ],
      price: "$219",
      savings: "Save $50",
    },
    {
      dealTitle: "Advanced Package",
      services: [
        "Unlimited Ducts",
        "Unlimited Vents",
        "Duct Cleaning",
        "Furnace Cleaning",
        "Dryer Vent Cleaning",
        "Return Line Cleaning",
      ],
      price: "$249",
      savings: "Save $75",
    },
    {
      dealTitle: "Elite Package",
      services: [
        "Unlimited Ducts",
        "Unlimited Vents",
        "Duct Cleaning",
        "Furnace Cleaning",
        "Dryer Vent Cleaning",
        "Return Line Cleaning",
        "Brushing Service",
      ],
      price: "$349",
      savings: "Save $100",
      popular: true,
    },
    {
      dealTitle: "Platinum Package",
      services: [
        "Unlimited Ducts",
        "Unlimited Vents",
        "Duct Cleaning",
        "Furnace Cleaning",
        "Dryer Vent Cleaning",
        "Return Line Cleaning",
        "Brushing Service",
        "AC Coil Cleaning",
      ],
      price: "$399",
      savings: "Save $130",
    },
  ],
};



export const pricingData = {
  ontario: [
    { service: 'Duct & Vents Cleaning', price: '$99' },
    { service: 'Brushing Service', price: '$99' },
    { service: 'Furnace', price: '$49' },
    { service: 'Dryer Vent', price: '$15' },
    { service: 'Return Line', price: '$25' },
    { service: 'AC Coil Cleaning', price: '$49' },
    { service: 'Complimentary Herbal Sanitization Spray', price: 'Included FREE' },
    { service: 'Main Line Cleaning', price: 'Included in packages' },
  ],
  alberta: [
    { service: 'Duct & Vents Cleaning', price: '$99' },
    { service: 'Brushing Service', price: '$99' },
    { service: 'Furnace', price: '$49' },
    { service: 'Dryer Vent', price: '$15' },
    { service: 'Return Line', price: '$25' },
    { service: 'AC Coil Cleaning', price: '$49' },
    { service: 'Complimentary Herbal Sanitization Spray', price: 'Included FREE' },
    { service: 'Main Line Cleaning', price: 'Included in packages' },
  ],
};